#on:
#  repository_dispatch:
#    types: [spec_release]
on: push

name: Generate VRChat API SDK

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate OpenAPI Client
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v16-${{ hashFiles('**/generate.sh') }}
          restore-keys: |
            ${{ runner.os }}-node-v16
      - name: Install OpenAPI Generator CLI
        run: npm install @openapitools/openapi-generator-cli
      - name: Generate SDK Client
        run: bash ./generate.sh
      - name: Check version number
        run: |
          echo "spec_version=$(grep "version" ./package.json | cut -d "\"" -f 4)" >> $GITHUB_ENV
      - name: Print version number
        run: echo ${{ env.spec_version }}
      - name: Deploy SDK back into main branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main
          folder: .
          commit-message: "Upgrade SDK to latest spec ${{ env.spec_version }}"
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ env.spec_version }}"
          commit-sha: main